############
##dev#######
############
spring: 
  datasource: 
    url: jdbc:mysql://localhost:3306/cms-seed?serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: wenzhen
    druid: 
      initial-size: 3
      max-active: 6
      min-idle: 3
#      max-wait: 30000
#      pool-prepared-statements: 
#      max-pool-prepared-statement-per-connection-size:  
#      max-open-prepared-statements:  #和上面的等价
      validation-query: SELECT 1
      validation-query-timeout: 10
      test-on-borrow: true
#      test-on-return: 
      test-while-idle: true
#      keep-alive: 
#      time-between-eviction-runs-millis: 
#      min-evictable-idle-time-millis: 
#      max-evictable-idle-time-millis: 
#      filters:  

#################
##Swagger配置####
#################
swagger2: 
  enable: true
  title: "cms-seed API dev"
  description: "dev环境接口"

  
  
  
  