export const data = 
{
    "levelKey": 0,
    "children": [
        {
            "levelKey": 1,
            "children": [
                {
                    "levelKey": 2,
                    "children": [
                        {
                            "levelKey": 3,
                            "children": [],
                            "hasChildren": false,
                            "key": 0,
                            "value": "空白",
                            "customerNumber": 1,
                            "taxIncome": 6500.0,
                            "noTaxIncome": 5752.22,
                            "noTaxSaleDiscount": 0.0,
                            "pureIncome": 0.0,
                            "noTaxCost": 0.0,
                            "noTaxPurchaseBenefit": 0.0,
                            "pureCost": 0.0,
                            "roughProfit": 0.0
                        },
                        {
                            "levelKey": 3,
                            "children": [],
                            "hasChildren": false,
                            "key": 2,
                            "value": "北京市",
                            "customerNumber": 11,
                            "taxIncome": 2985991.3,
                            "noTaxIncome": 2642470.16,
                            "noTaxSaleDiscount": 0.0,
                            "pureIncome": 0.0,
                            "noTaxCost": 0.0,
                            "noTaxPurchaseBenefit": 0.0,
                            "pureCost": 0.0,
                            "roughProfit": 0.0
                        },
                        {
                            "levelKey": 3,
                            "children": [],
                            "hasChildren": false,
                            "key": 3,
                            "value": "天津市",
                            "customerNumber": 3,
                            "taxIncome": 126390.0,
                            "noTaxIncome": 111849.57,
                            "noTaxSaleDiscount": 0.0,
                            "pureIncome": 0.0,
                            "noTaxCost": 0.0,
                            "noTaxPurchaseBenefit": 0.0,
                            "pureCost": 0.0,
                            "roughProfit": 0.0
                        },
                        {
                            "levelKey": 3,
                            "children": [],
                            "hasChildren": false,
                            "key": 4,
                            "value": "上海市",
                            "customerNumber": 1,
                            "taxIncome": 370008.0,
                            "noTaxIncome": 327440.71,
                            "noTaxSaleDiscount": 0.0,
                            "pureIncome": 0.0,
                            "noTaxCost": 0.0,
                            "noTaxPurchaseBenefit": 0.0,
                            "pureCost": 0.0,
                            "roughProfit": 0.0
                        },
                        {
                            "levelKey": 3,
                            "children": [],
                            "hasChildren": false,
                            "key": 5,
                            "value": "重庆市",
                            "customerNumber": 37,
                            "taxIncome": 7454285.45,
                            "noTaxIncome": 6596712.81,
                            "noTaxSaleDiscount": 0.0,
                            "pureIncome": 0.0,
                            "noTaxCost": 0.0,
                            "noTaxPurchaseBenefit": 0.0,
                            "pureCost": 0.0,
                            "roughProfit": 0.0
                        },
                        {
                            "levelKey": 3,
                            "children": [],
                            "hasChildren": false,
                            "key": 8,
                            "value": "内蒙古自治区",
                            "customerNumber": 3,
                            "taxIncome": 193400.0,
                            "noTaxIncome": 171150.42,
                            "noTaxSaleDiscount": 0.0,
                            "pureIncome": 0.0,
                            "noTaxCost": 0.0,
                            "noTaxPurchaseBenefit": 0.0,
                            "pureCost": 0.0,
                            "roughProfit": 0.0
                        },
                        {
                            "levelKey": 3,
                            "children": [],
                            "hasChildren": false,
                            "key": 9,
                            "value": "广西壮族自治区",
                            "customerNumber": 22,
                            "taxIncome": 4903894.01,
                            "noTaxIncome": 4339729.25,
                            "noTaxSaleDiscount": 0.0,
                            "pureIncome": 0.0,
                            "noTaxCost": 0.0,
                            "noTaxPurchaseBenefit": 0.0,
                            "pureCost": 0.0,
                            "roughProfit": 0.0
                        },
                        {
                            "levelKey": 3,
                            "children": [],
                            "hasChildren": false,
                            "key": 10,
                            "value": "西藏自治区",
                            "customerNumber": 5,
                            "taxIncome": 776393.97,
                            "noTaxIncome": 687074.32,
                            "noTaxSaleDiscount": 0.0,
                            "pureIncome": 0.0,
                            "noTaxCost": 0.0,
                            "noTaxPurchaseBenefit": 0.0,
                            "pureCost": 0.0,
                            "roughProfit": 0.0
                        },
                        {
                            "levelKey": 3,
                            "children": [],
                            "hasChildren": false,
                            "key": 12,
                            "value": "新疆维吾尔自治区",
                            "customerNumber": 2,
                            "taxIncome": 21080.0,
                            "noTaxIncome": 18654.87,
                            "noTaxSaleDiscount": 0.0,
                            "pureIncome": 0.0,
                            "noTaxCost": 0.0,
                            "noTaxPurchaseBenefit": 0.0,
                            "pureCost": 0.0,
                            "roughProfit": 0.0
                        },
                        {
                            "levelKey": 3,
                            "children": [],
                            "hasChildren": false,
                            "key": 13,
                            "value": "河北省",
                            "customerNumber": 19,
                            "taxIncome": 4375768.0,
                            "noTaxIncome": 3875707.68,
                            "noTaxSaleDiscount": 0.0,
                            "pureIncome": 0.0,
                            "noTaxCost": 0.0,
                            "noTaxPurchaseBenefit": 0.0,
                            "pureCost": 0.0,
                            "roughProfit": 0.0
                        },
                        {
                            "levelKey": 3,
                            "children": [],
                            "hasChildren": false,
                            "key": 14,
                            "value": "山西省",
                            "customerNumber": 7,
                            "taxIncome": 1570978.0,
                            "noTaxIncome": 1390246.0,
                            "noTaxSaleDiscount": 0.0,
                            "pureIncome": 0.0,
                            "noTaxCost": 0.0,
                            "noTaxPurchaseBenefit": 0.0,
                            "pureCost": 0.0,
                            "roughProfit": 0.0
                        },
                        {
                            "levelKey": 3,
                            "children": [],
                            "hasChildren": false,
                            "key": 15,
                            "value": "辽宁省",
                            "customerNumber": 10,
                            "taxIncome": 701253.4,
                            "noTaxIncome": 620578.19,
                            "noTaxSaleDiscount": 0.0,
                            "pureIncome": 0.0,
                            "noTaxCost": 0.0,
                            "noTaxPurchaseBenefit": 0.0,
                            "pureCost": 0.0,
                            "roughProfit": 0.0
                        },
                        {
                            "levelKey": 3,
                            "children": [],
                            "hasChildren": false,
                            "key": 16,
                            "value": "吉林省",
                            "customerNumber": 26,
                            "taxIncome": 3428126.11,
                            "noTaxIncome": 3033739.93,
                            "noTaxSaleDiscount": 0.0,
                            "pureIncome": 0.0,
                            "noTaxCost": 0.0,
                            "noTaxPurchaseBenefit": 0.0,
                            "pureCost": 0.0,
                            "roughProfit": 0.0
                        },
                        {
                            "levelKey": 3,
                            "children": [],
                            "hasChildren": false,
                            "key": 17,
                            "value": "黑龙江省",
                            "customerNumber": 10,
                            "taxIncome": 1325139.18,
                            "noTaxIncome": 1172689.59,
                            "noTaxSaleDiscount": 0.0,
                            "pureIncome": 0.0,
                            "noTaxCost": 0.0,
                            "noTaxPurchaseBenefit": 0.0,
                            "pureCost": 0.0,
                            "roughProfit": 0.0
                        },
                        {
                            "levelKey": 3,
                            "children": [],
                            "hasChildren": false,
                            "key": 18,
                            "value": "江苏省",
                            "customerNumber": 27,
                            "taxIncome": 3411502.5,
                            "noTaxIncome": 3019030.38,
                            "noTaxSaleDiscount": 0.0,
                            "pureIncome": 0.0,
                            "noTaxCost": 0.0,
                            "noTaxPurchaseBenefit": 0.0,
                            "pureCost": 0.0,
                            "roughProfit": 0.0
                        },
                        {
                            "levelKey": 3,
                            "children": [],
                            "hasChildren": false,
                            "key": 19,
                            "value": "浙江省",
                            "customerNumber": 14,
                            "taxIncome": 7812870.0,
                            "noTaxIncome": 6914044.28,
                            "noTaxSaleDiscount": 0.0,
                            "pureIncome": 0.0,
                            "noTaxCost": 0.0,
                            "noTaxPurchaseBenefit": 0.0,
                            "pureCost": 0.0,
                            "roughProfit": 0.0
                        },
                        {
                            "levelKey": 3,
                            "children": [],
                            "hasChildren": false,
                            "key": 20,
                            "value": "安徽省",
                            "customerNumber": 16,
                            "taxIncome": 1917659.49,
                            "noTaxIncome": 1697906.58,
                            "noTaxSaleDiscount": 0.0,
                            "pureIncome": 0.0,
                            "noTaxCost": 0.0,
                            "noTaxPurchaseBenefit": 0.0,
                            "pureCost": 0.0,
                            "roughProfit": 0.0
                        },
                        {
                            "levelKey": 3,
                            "children": [],
                            "hasChildren": false,
                            "key": 21,
                            "value": "福建省",
                            "customerNumber": 3,
                            "taxIncome": 45400.0,
                            "noTaxIncome": 40177.0,
                            "noTaxSaleDiscount": 0.0,
                            "pureIncome": 0.0,
                            "noTaxCost": 0.0,
                            "noTaxPurchaseBenefit": 0.0,
                            "pureCost": 0.0,
                            "roughProfit": 0.0
                        },
                        {
                            "levelKey": 3,
                            "children": [],
                            "hasChildren": false,
                            "key": 22,
                            "value": "江西省",
                            "customerNumber": 27,
                            "taxIncome": 2719235.21,
                            "noTaxIncome": 2406402.82,
                            "noTaxSaleDiscount": 0.0,
                            "pureIncome": 0.0,
                            "noTaxCost": 0.0,
                            "noTaxPurchaseBenefit": 0.0,
                            "pureCost": 0.0,
                            "roughProfit": 0.0
                        },
                        {
                            "levelKey": 3,
                            "children": [],
                            "hasChildren": false,
                            "key": 23,
                            "value": "山东省",
                            "customerNumber": 28,
                            "taxIncome": 1623376.82,
                            "noTaxIncome": 1453107.26,
                            "noTaxSaleDiscount": 0.0,
                            "pureIncome": 0.0,
                            "noTaxCost": 0.0,
                            "noTaxPurchaseBenefit": 0.0,
                            "pureCost": 0.0,
                            "roughProfit": 0.0
                        },
                        {
                            "levelKey": 3,
                            "children": [],
                            "hasChildren": false,
                            "key": 24,
                            "value": "河南省",
                            "customerNumber": 28,
                            "taxIncome": 3581618.27,
                            "noTaxIncome": 3179368.06,
                            "noTaxSaleDiscount": 0.0,
                            "pureIncome": 0.0,
                            "noTaxCost": 0.0,
                            "noTaxPurchaseBenefit": 0.0,
                            "pureCost": 0.0,
                            "roughProfit": 0.0
                        },
                        {
                            "levelKey": 3,
                            "children": [],
                            "hasChildren": false,
                            "key": 25,
                            "value": "湖北省",
                            "customerNumber": 47,
                            "taxIncome": 5978423.89,
                            "noTaxIncome": 5291417.16,
                            "noTaxSaleDiscount": 0.0,
                            "pureIncome": 0.0,
                            "noTaxCost": 0.0,
                            "noTaxPurchaseBenefit": 0.0,
                            "pureCost": 0.0,
                            "roughProfit": 0.0
                        },
                        {
                            "levelKey": 3,
                            "children": [],
                            "hasChildren": false,
                            "key": 26,
                            "value": "湖南省",
                            "customerNumber": 22,
                            "taxIncome": 2903371.8,
                            "noTaxIncome": 2570860.86,
                            "noTaxSaleDiscount": 0.0,
                            "pureIncome": 0.0,
                            "noTaxCost": 0.0,
                            "noTaxPurchaseBenefit": 0.0,
                            "pureCost": 0.0,
                            "roughProfit": 0.0
                        },
                        {
                            "levelKey": 3,
                            "children": [],
                            "hasChildren": false,
                            "key": 27,
                            "value": "广东省",
                            "customerNumber": 43,
                            "taxIncome": 14716266.15,
                            "noTaxIncome": 13024793.2,
                            "noTaxSaleDiscount": 0.0,
                            "pureIncome": 0.0,
                            "noTaxCost": 0.0,
                            "noTaxPurchaseBenefit": 0.0,
                            "pureCost": 0.0,
                            "roughProfit": 0.0
                        },
                        {
                            "levelKey": 3,
                            "children": [],
                            "hasChildren": false,
                            "key": 28,
                            "value": "海南省",
                            "customerNumber": 7,
                            "taxIncome": 440255.0,
                            "noTaxIncome": 389606.19,
                            "noTaxSaleDiscount": 0.0,
                            "pureIncome": 0.0,
                            "noTaxCost": 0.0,
                            "noTaxPurchaseBenefit": 0.0,
                            "pureCost": 0.0,
                            "roughProfit": 0.0
                        },
                        {
                            "levelKey": 3,
                            "children": [],
                            "hasChildren": false,
                            "key": 29,
                            "value": "四川省",
                            "customerNumber": 279,
                            "taxIncome": 113677135.29,
                            "noTaxIncome": 100697214.63,
                            "noTaxSaleDiscount": 0.0,
                            "pureIncome": 0.0,
                            "noTaxCost": 0.0,
                            "noTaxPurchaseBenefit": 0.0,
                            "pureCost": 0.0,
                            "roughProfit": 0.0
                        },
                        {
                            "levelKey": 3,
                            "children": [],
                            "hasChildren": false,
                            "key": 30,
                            "value": "贵州省",
                            "customerNumber": 15,
                            "taxIncome": 1152495.0,
                            "noTaxIncome": 1019907.07,
                            "noTaxSaleDiscount": 0.0,
                            "pureIncome": 0.0,
                            "noTaxCost": 0.0,
                            "noTaxPurchaseBenefit": 0.0,
                            "pureCost": 0.0,
                            "roughProfit": 0.0
                        },
                        {
                            "levelKey": 3,
                            "children": [],
                            "hasChildren": false,
                            "key": 31,
                            "value": "云南省",
                            "customerNumber": 14,
                            "taxIncome": 3669903.92,
                            "noTaxIncome": 3250282.53,
                            "noTaxSaleDiscount": 0.0,
                            "pureIncome": 0.0,
                            "noTaxCost": 0.0,
                            "noTaxPurchaseBenefit": 0.0,
                            "pureCost": 0.0,
                            "roughProfit": 0.0
                        },
                        {
                            "levelKey": 3,
                            "children": [],
                            "hasChildren": false,
                            "key": 32,
                            "value": "陕西省",
                            "customerNumber": 15,
                            "taxIncome": 2182798.5,
                            "noTaxIncome": 1931680.08,
                            "noTaxSaleDiscount": 0.0,
                            "pureIncome": 0.0,
                            "noTaxCost": 0.0,
                            "noTaxPurchaseBenefit": 0.0,
                            "pureCost": 0.0,
                            "roughProfit": 0.0
                        },
                        {
                            "levelKey": 3,
                            "children": [],
                            "hasChildren": false,
                            "key": 33,
                            "value": "甘肃省",
                            "customerNumber": 12,
                            "taxIncome": 1290208.15,
                            "noTaxIncome": 1142027.14,
                            "noTaxSaleDiscount": 0.0,
                            "pureIncome": 0.0,
                            "noTaxCost": 0.0,
                            "noTaxPurchaseBenefit": 0.0,
                            "pureCost": 0.0,
                            "roughProfit": 0.0
                        },
                        {
                            "hasChildren": false,
                            "customerNumber": 754,
                            "taxIncome": 195361727.41,
                            "noTaxIncome": 173021620.96,
                            "noTaxSaleDiscount": 0.0,
                            "pureIncome": 0.0,
                            "noTaxCost": 0.0,
                            "noTaxPurchaseBenefit": 0.0,
                            "pureCost": 0.0,
                            "roughProfit": 0.0,
                            "value": "汇总"
                        }
                    ],
                    "hasChildren": true,
                    "key": 0,
                    "value": "线上"
                },
                {
                    "hasChildren": false,
                    "customerNumber": 754,
                    "taxIncome": 195361727.41,
                    "noTaxIncome": 173021620.96,
                    "noTaxSaleDiscount": 0.0,
                    "pureIncome": 0.0,
                    "noTaxCost": 0.0,
                    "noTaxPurchaseBenefit": 0.0,
                    "pureCost": 0.0,
                    "roughProfit": 0.0,
                    "value": "汇总"
                }
            ],
            "hasChildren": true,
            "key": 201907,
            "value": "2019-07"
        },
        {
            "levelKey": 1,
            "children": [
                {
                    "levelKey": 2,
                    "children": [],
                    "hasChildren": false,
                    "key": 0,
                    "value": "线上",
                    "customerNumber": 1,
                    "taxIncome": 26208.0,
                    "noTaxIncome": 26208.0,
                    "noTaxSaleDiscount": 0.0,
                    "pureIncome": 0.0,
                    "noTaxCost": 0.0,
                    "noTaxPurchaseBenefit": 1572.48,
                    "pureCost": -1572.48,
                    "roughProfit": 0.0
                },
                {
                    "hasChildren": false,
                    "customerNumber": 1,
                    "taxIncome": 26208.0,
                    "noTaxIncome": 26208.0,
                    "noTaxSaleDiscount": 0.0,
                    "pureIncome": 0.0,
                    "noTaxCost": 0.0,
                    "noTaxPurchaseBenefit": 1572.48,
                    "pureCost": -1572.48,
                    "roughProfit": 0.0,
                    "value": "汇总"
                }
            ],
            "hasChildren": true,
            "key": 201911,
            "value": "2019-11"
        },
        {
            "levelKey": 1,
            "children": [
                {
                    "levelKey": 2,
                    "children": [],
                    "hasChildren": false,
                    "key": 0,
                    "value": "线下",
                    "customerNumber": 733,
                    "taxIncome": 206486098.64,
                    "noTaxIncome": 182948203.11,
                    "noTaxSaleDiscount": 0.0,
                    "pureIncome": 0.0,
                    "noTaxCost": 0.0,
                    "noTaxPurchaseBenefit": 0.0,
                    "pureCost": 0.0,
                    "roughProfit": 0.0
                },
                {
                    "hasChildren": false,
                    "customerNumber": 733,
                    "taxIncome": 206486098.64,
                    "noTaxIncome": 182948203.11,
                    "noTaxSaleDiscount": 0.0,
                    "pureIncome": 0.0,
                    "noTaxCost": 0.0,
                    "noTaxPurchaseBenefit": 0.0,
                    "pureCost": 0.0,
                    "roughProfit": 0.0,
                    "value": "汇总"
                }
            ],
            "hasChildren": true,
            "key": 201908,
            "value": "2019-08"
        },
        {
            "hasChildren": false,
            "customerNumber": 1488,
            "taxIncome": 401874034.05,
            "noTaxIncome": 355996032.07,
            "noTaxSaleDiscount": 0.0,
            "pureIncome": 0.0,
            "pureIncomeProportion": 1,
            "noTaxCost": 0.0,
            "noTaxPurchaseBenefit": 1572.48,
            "pureCost": -1572.48,
            "roughProfit": 0.0,
            "roughProfitProportion": 1,
            "value": "汇总"
        }
    ],
    "hasChildren": true
};